mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('GamerAsia/', include('webstore.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webstore/urls.py
from django.urls import path

from . import views

app_name = "webstore"

urlpatterns = [
    path("page/<int:page_number>", views.index, name="index"),
    path("profile", views.profile, name="profile"),
    path("save_user_profile", views.save_user_profile, name="save_user_profile"),
    # make new item for the owner
    path("new_item", views.new_item, name="new_item"),
    path("item_delete/<int:item_id>", views.item_delete, name="item_delete"),
    path("rate_item/<int:item_id>/<int:rate_score>", views.rate_item, name="rate_item"),
    path("item_page/<int:item_id>", views.item_page, name="item_page"),
    # handling shopping cart:
    path("cart/add/<int:item_id>", views.cart_add, name="cart_add"),
    path("cart/item_clear/<int:item_id>", views.item_clear, name="item_clear"),
    path("cart/item_increment/<int:item_id>", views.item_increment, name="item_increment"),
    path("cart/item_decrement/<int:item_id>", views.item_decrement, name="item_decrement"),
    path("cart/cart_clear", views.cart_clear, name="cart_clear"),
    path("cart/cart_detail/<int:page_number>", views.cart_detail, name="cart_detail"),

    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
]

webstore/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils import timezone


class User(AbstractUser):
    is_admin = models.BooleanField(default=False)

class client(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="client_profile")
    delivery_address = models.TextField(blank=True, max_length=500)
    birthday = models.DateTimeField()
    # consider implementing bought history

class comment(models.Model):
    comment_content = models.TextField(max_length=2000)
    commenter = models.ForeignKey(User, on_delete=models.CASCADE, related_name="client_comment")

class rating(models.Model):
    rater = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_rating")
    rating = models.PositiveIntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(5)])

class item(models.Model):
    # item basic information
    item_name = models.CharField(max_length=100)
    item_price = models.FloatField(default=0, validators=[MinValueValidator(0)])
    item_Description = models.TextField(max_length=1000)
    item_footnote = models.TextField(max_length=100, blank=True)
    number_in_store = models.PositiveIntegerField(default=0)
    # handling the rating
    rating = models.ManyToManyField(rating, blank=True, related_name="item")
    rating_average = models.FloatField(default=0, validators=[MinValueValidator(0), MaxValueValidator(5)])
    number_of_rating = models.PositiveIntegerField(default=0)

    picture = models.ImageField(upload_to='images/', blank=True)
    comments = models.ManyToManyField(comment, blank=True, related_name="item")

webstore/views.py
import json
from django import forms
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.core.paginator import Paginator
from datetime import datetime, date, time
from django.core.exceptions import ObjectDoesNotExist
from .models import User, client, comment, item, rating

# Constant for pages
ITEM_PER_INDEX = 12
MORE_ITEM_PER_INDEX = 30

# my new data type to handle shopping cart
'''class cart(object):
    def __init__(self, item_id, item_number):
        self.item_id = item_id
        self.item_number = item_number

    def toJSON(self):
        return json.dumps(self, default=lambda o:o.__dict__)
'''

# Create your views here.

def index(request, page_number):
    # shopping cart management
    # create session
    request.session["cart"] = createSession(request)
    items = Paginator(item.objects.all(), ITEM_PER_INDEX)
    
    return render(request, "webstore/index.html", {
        "items": items.page(page_number).object_list,
        "page_number": page_number,
        "total_page": items.num_pages,
        "num_in_cart": len(request.session["cart"]),
    })

def item_page(request, item_id):
    # shopping cart management
    # create session
    request.session["cart"] = createSession(request)
    item_data = item.objects.get(id=item_id)

    return render(request, "webstore/item_page.html", {
        "item_data": item_data,
        "num_in_cart": len(request.session["cart"]),
    })

def login_view(request):
    if request.method == "POST":
        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("webstore:index", kwargs={'page_number':1}))
        else:
            return render(request, "webstore/login.html", {
                "message": "Invalid username / password."
            })
    else:
        return render(request, "webstore/login.html")

@login_required
def rate_item(request, item_id, rate_score):
    item_repr = item.objects.get(id=item_id)
    user_rated = True
    try: 
        user_rating = item_repr.rating.get(rater = request.user)
    except ObjectDoesNotExist:
        user_rating = None
        user_rated = False

    # check if the rate_score is valid
    valid_rate = False
    if rate_score >= 0 and rate_score <= 5:
        valid_rate = True

    if user_rated == False and valid_rate == True:
        item_repr.rating_average = item_repr.rating_average * item_repr.number_of_rating + rate_score
        item_repr.number_of_rating = item_repr.number_of_rating + 1
        item_repr.rating_average = item_repr.rating_average / item_repr.number_of_rating
        item_repr.save()

        user_new_rating = rating(rater=request.user, rating=rate_score)
        user_new_rating.save()
        item_repr.rating.add(user_new_rating)
    return HttpResponseRedirect(reverse("webstore:item_page", kwargs={'item_id': item_id}))

@login_required
def new_item(request):
    # form data
    class itemForm(forms.Form):
        # item basic information
        item_name = forms.CharField(label="item name", max_length=100)
        item_price = forms.FloatField(min_value=0)
        item_footnote = forms.CharField(label="item footnote", widget=forms.Textarea(attrs={'rows': 4}), max_length=100)
        item_Description = forms.CharField(widget=forms.Textarea(attrs={'rows': 4}), max_length=1000)
        number_in_store = forms.IntegerField(min_value=0)
        picture = forms.ImageField()

        item_name.widget.attrs.update({'class':'form-control register_and_login', 'required':'required', 'style': 'height: 32.5px; font-size: 14px; border: 1px solid #9B9791'})
        item_price.widget.attrs.update({'class':'form-control register_and_login', 'required':'required', 'style': 'height: 32.5px; font-size: 14px; border: 1px solid #9B9791'})
        item_footnote.widget.attrs.update({'class':'form-control register_and_login', 'style': 'height: 32.5px; font-size: 14px; border: 1px solid #9B9791'})
        item_Description.widget.attrs.update({'class':'form-control register_and_login', 'style': 'height: 32.5px; font-size: 14px; border: 1px solid #9B9791'})
        number_in_store.widget.attrs.update({'class':'form-control register_and_login', 'required':'required', 'style': 'height: 32.5px; font-size: 14px; border: 1px solid #9B9791'})
        picture.widget.attrs.update({'class':'photo_upload form-control register_and_login', 'required': 'False', 'style': 'height: 32.5px; font-size: 14px; border: 1px solid #9B9791; padding: 2.5px'})

    # filter out non-logged-in users
    if request.user.is_authenticated:
        # filter out non-admin users
        if request.user.is_admin:
            if request.method == "POST": 
                # need to add request.FILES if there were images.
                form = itemForm(request.POST, request.FILES)
                # check whether it's valid
                if form.is_valid():

                    name = form.cleaned_data["item_name"]
                    price = form.cleaned_data["item_price"]
                    footnote = form.cleaned_data["item_footnote"]
                    description = form.cleaned_data["item_Description"]
                    number_in_store = form.cleaned_data["number_in_store"]
                    picture = form.cleaned_data["picture"]


                    New_item = item.objects.create(
                        item_name = name,
                        item_price = price,
                        item_footnote = footnote,
                        item_Description = description,
                        number_in_store = number_in_store,
                        picture = picture,
                    )
                    New_item.save()
                    return HttpResponseRedirect(reverse("webstore:index", kwargs = {'page_number':1}))
            else:
                form = itemForm()

        else:
            # filter out non-admin users, return them back to index page
            return HttpResponseRedirect(reverse("webstore:index", kwargs = {'page_number':1}))    
    else:
        # filter out non-logged-in users, return them back to index page
        return HttpResponseRedirect(reverse("webstore:index", kwargs = {'page_number':1}))
    return render(request, "webstore/new_item.html", {
                "form": form,
                "num_in_cart": len(request.session["cart"]),
            })

@login_required
def item_delete(request, item_id):
    # only admin can delete item
    if request.user.is_admin:
        item_repr = item.objects.get(id=item_id)
        item_repr.delete()

    return HttpResponseRedirect(reverse("webstore:index", kwargs = {'page_number':1}))

# cart handling
def cart_add(request, item_id):
    # shopping cart management
    # create session
    # Django session list cannot append class objects
    request.session["cart"] = createSession(request)

    # handling add to cart
    request.session["cart"].append(item_id)

    return HttpResponseRedirect(reverse("webstore:item_page", kwargs = {'item_id':item_id}))


def item_clear(request, item_id):
    # shopping cart management
    # create session
    request.session["cart"] = createSession(request)
    while item_id in request.session["cart"]:
        request.session["cart"].remove(item_id)
    return HttpResponseRedirect(reverse("webstore:cart_detail", kwargs = {'page_number':1}))


def item_increment(request, item_id):
    # shopping cart management
    # create session
    request.session["cart"] = createSession(request)
    request.session["cart"].append(item_id)
    return HttpResponseRedirect(reverse("webstore:cart_detail", kwargs = {'page_number':1}))


def item_decrement(request, item_id):
    # shopping cart management
    # create session
    request.session["cart"] = createSession(request)
    request.session["cart"].remove(item_id)
    return HttpResponseRedirect(reverse("webstore:cart_detail", kwargs = {'page_number':1}))


def cart_clear(request):
    # shopping cart management
    # create session
    request.session["cart"] = createSession(request)
    request.session["cart"] = []
    return HttpResponseRedirect(reverse("webstore:index", kwargs={'page_number':1}))
    

def cart_detail(request, page_number):
    # shopping cart management
    # create session
    request.session["cart"] = createSession(request)
    items = Paginator(item.objects.filter(id__in=request.session["cart"]), ITEM_PER_INDEX)

    return render(request, "webstore/cart.html", {
        "cart": request.session["cart"],
        "items": items.page(page_number).object_list,
        "page_number": page_number,
        "total_page": items.num_pages,
        "num_in_cart": len(request.session["cart"]),
    })

@login_required
def save_user_profile(request):
    if request.method == "POST":
        user = request.user

        em = request.POST["email"]
        bday = request.POST["birthday"]
        add = request.POST["address"]

        client_info = client.objects.get(user=request.user)
        client_info.delivery_address = add
        client_info.birthday = bday
        client_info.save()

        user.email = em
        user.save()
    return HttpResponseRedirect(reverse("webstore:profile"))

@login_required
def profile(request):
    # shopping cart management
    # create session
    request.session["cart"] = createSession(request)

    # return the user's profile
    # consider making bought history
    if request.user.is_authenticated:
        user_information = client.objects.get(user=request.user)
        user_email = request.user.email

webstore/templates/webstore/cart.html
{% extends "webstore/layout.html" %}
{% load static %}

{% block body %}
<div id="outer_container">
    {% for i in items %}
        <div class="box" id="{{ i.id }}" onclick="location.href=`{% url 'webstore:item_page' item_id=i.id %}`;">
                <div class="photo" style="justify-content: center; align-items: center; display: flex;">
                    <img src="{{ i.picture.url }}" style="max-width: 270px; max-height: 200px">
                </div>
                <div class="name">
                    <h6>{{ i.item_name }}</h6>
                </div>
                <div class="price" style="color: #B51B0A;">
                    ${{ i.item_price }}
                </div>
                <div class="rating">
                    <div class="item_page_rating">
                        <span class="heading">Rating: </span>
                        <span class="fa fa-star first {% if i.rating_average > 0.5 %} checked {% endif %}"></span>
                        <span class="fa fa-star second {% if i.rating_average > 1.5 %} checked {% endif %}"></span>
                        <span class="fa fa-star third {% if i.rating_average > 2.5 %} checked {% endif %}"></span>
                        <span class="fa fa-star fourth {% if i.rating_average > 3.5 %} checked {% endif %}"></span>
                        <span class="fa fa-star fifth {% if i.rating_average > 4.5 %} checked {% endif %}"></span>
                        <span style="color: #515151;font-size: 14px;"> (rating: {{ i.rating_average|floatformat:1 }})</span>

                    </div>
                </div>
                <div style="position: relative; all: initial; clear: both; padding-left: 20px; padding-right: 20px;">
                    <form class="" style="all: initial;" action="{% url 'webstore:item_decrement' i.id %}">
                        <input type="image" width="16" height="16" src="https://www.flaticon.com/svg/static/icons/svg/1828/1828905.svg" class="loaded" alt="submit">
                    </form>
                    <span class="item_num_in_cart"></span>
                    <script>
                        function implement_cart_itemNumber(session_cart_list_inString, item_id) {
                        number_of_item = 0;
                        item_id_digit = item_id.length
                        for (i=0; i<session_cart_list_inString.length; i++) {
                            if (session_cart_list_inString.substring(i, i+item_id_digit) == item_id) {
                                number_of_item++
                            };
                        };
                        return number_of_item;
                        };
                        implement_cart_itemNumber('{{ cart }}', '{{ i.id }}');
                        document.getElementById("{{ i.id }}").getElementsByClassName("item_num_in_cart")[0].innerHTML = implement_cart_itemNumber('{{ cart }}', '{{ i.id }}');
                    </script>

                    <script>
                        implement_cart_itemNumber('{{ cart }}', '{{ i.id }}');
                    </script>

                    <form class="" style="all: initial;" action="{% url 'webstore:item_increment' i.id %}">
                        <input type="image" width="16" height="16" src="https://www.flaticon.com/svg/static/icons/svg/748/748113.svg" class="loaded" alt="submit">
                    </form>
                </div>
                <div style="all: initial;">
                    <form class="cart_and_item" style="all: initial;" action="{% url 'webstore:item_clear' i.id %}">
                        <input class="btn cart_and_item" style="font-size: 14px;" type="submit" value="remove">
                    </form>
                </div>
                
        </div>
    {% endfor %}
</div>

    <!-- Pagination toolbar -->
    <div>
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                <li class="page-item {% if page_number == 1 %} disabled {% endif %}">
                    <a class="page-link" href="{% url 'webstore:cart_detail' page_number=page_number|add:-1 %}" tabindex="-1">Previous</a>
                </li>
                {% if page_number > 2%}
                <li class="page-item"><a class="page-link" href="{% url 'webstore:cart_detail' page_number|add:-2 %}">{{ page_number|add:-2 }}</a></li>
                {% endif %}
                {% if page_number > 1%}
                <li class="page-item"><a class="page-link" href="{% url 'webstore:cart_detail' page_number|add:-1 %}">{{ page_number|add:-1 }}</a></li>
                {% endif %}
                <li class="page-item"><a class="page-link" style="background-color: rgba(251, 219, 190, 1); box-shadow: 0px 0px 12.5px 0px #F2B983 inset;" href="{% url 'webstore:cart_detail' page_number %}">{{ page_number }}</a></li>
                {% if not page_number|add:1 > total_page %}
                <li class="page-item"><a class="page-link" href="{% url 'webstore:cart_detail' page_number|add:1 %}">{{ page_number|add:1 }}</a></li>
                {% endif %}
                {% if not page_number|add:2 > total_page %}
                <li class="page-item"><a class="page-link" href="{% url 'webstore:cart_detail' page_number|add:2 %}">{{ page_number|add:2 }}</a></li>
                {% endif %}
                <li class="page-item">
                <li class="page-item {% if page_number == total_page %} disabled {% endif %}">
                    <a class="page-link" href="{% url 'webstore:cart_detail' page_number=page_number|add:1 %}">Next</a>
                </li>
            </ul>
        </nav>
    </div>
    <!-- End Pagination toolbar -->
{% endblock %}

{% block script %}
{% endblock %}

webstore/templates/webstore/item_page.html
{% extends "webstore/layout.html" %}
{% load static %}

{% block body %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <div class="item_page_box">
        <div class="item_page_photo" style="justify-content: center; align-items: center; display: flex;">
            <img src="{{ item_data.picture.url }}" style="max-width: 270px; max-height: 200px">
        </div>
        <div class="item_page_content">
            <div class="item_page_name">
                <div style="display: inline-block; width: auto">
                    <h4 style="display: inline-block;">{{ item_data.item_name }}</h4>
                </div>
                {% if user.is_admin %}
                <form action="{% url 'webstore:item_delete' item_data.id %}" style="float: right">
                    <input class="btn cart_and_item_delete" style="font-size: 14px" type="submit" value="Delete">
                </form>
                {% endif %}
                <form action="{% url 'webstore:cart_add' item_data.id %}" style="float: right">
                    <input class="btn cart_and_item" style="font-size: 14px;" type="submit" value="Add to Cart">
                </form>
                
            </div>
            <div class="item_page_price">
                Price: <span style="color: #B51B0A;">${{ item_data.item_price }}</span>
            </div>
            <div class="item_page_rating">
                <span id="rating_star_outerbox" class="heading">Rating: 
                <span id="rating_star_box">
                    <span class="fa fa-star first {% if item_data.rating_average > 0.5 %} checked {% endif %}"></span>
                    <span class="fa fa-star second {% if item_data.rating_average > 1.5 %} checked {% endif %}"></span>
                    <span class="fa fa-star third {% if item_data.rating_average > 2.5 %} checked {% endif %}"></span>
                    <span class="fa fa-star fourth {% if item_data.rating_average > 3.5 %} checked {% endif %}"></span>
                    <span class="fa fa-star fifth {% if item_data.rating_average > 4.5 %} checked {% endif %}"></span>
                <span style="color: #515151;font-size: 14px;"> (rating: {{ item_data.rating_average|floatformat:1 }})</span>
                </span>
                </span>
            </div>
            <div style="{% if item_data.number_in_store < 10%}color: #FF381C {% else %}color: #14EB38 {% endif %};">
                {% if user.is_admin%} Number in Store: {{ item_data.number_in_store }} {% endif %}
                
            </div>
            <div class="item_page_footnote">
                <label>Description: </label>
                {{ item_data.item_Description }}
            </div>
        </div>
        {% if user.is_authenticated %}
        <script>

            var star1 = document.getElementsByClassName("first")[0];
            var star2 = document.getElementsByClassName("second")[0];
            var star3 = document.getElementsByClassName("third")[0];
            var star4 = document.getElementsByClassName("fourth")[0];
            var star5 = document.getElementsByClassName("fifth")[0];
            starlist = [star1, star2, star3, star4, star5];
            var starbox = document.getElementById('rating_star_outerbox');

            star_hovering_detect(star1, 'mouseover', 1);
            star_hovering_detect(star2, 'mouseover', 2);
            star_hovering_detect(star3, 'mouseover', 3);
            star_hovering_detect(star4, 'mouseover', 4);
            star_hovering_detect(star5, 'mouseover', 5);
            origin_rating(starlist, starbox, 'mouseout');

            change_rating(starlist);

            function change_rating(starlist) {
                starlist.forEach((item, rate_score) => {
                    item.addEventListener('click', (__, i=rate_score+1) => {
                        fetch(`/GamerAsia/rate_item/{{ item_data.id }}/${i}`, {redirect: 'follow'})
                        .then(response => {
                            if (response.redirected) {
                                window.location.href = response.url;
                            }
                        })
                        .catch(function(err) {
                            console.info(err + " url: " + url);
                        }) 
                    })
                })
            }

            function star_hovering_detect(elem, event, star_number) {
                elem.addEventListener(event, () => {
                    if (event == 'mouseover') {
                        star_light_up(star_number);
                    }
                    if (event == 'mouseout') {
                        return false;
                    }
                })
            }

            function origin_rating(starlist, starbox, event) {
                starbox.addEventListener(event, () => {
                    if (event == 'mouseout') {
                        for (i=0; i < starlist.length; i++) {
                            if (parseFloat('{{ item_data.rating_average }}') > i + 1 / 2) {
                                starlist[i].classList.add('checked');
                            }
                            else {
                                starlist[i].classList.remove('checked');
                            }
                        }
                    }
                });
            }

            function star_light_up(star_number) {
                for (i=1; i <= 5; i++) {
                    switch (i) {
                        case 1: 
                            class_name = 'first';
                            break;
                        case 2: 
                            class_name = 'second';
                            break;
                        case 3: 
                            class_name = 'third';
                            break;
                        case 4: 
                            class_name = 'fourth';
                            break;
                        case 5: 
                            class_name = 'fifth';
                            break;
                    }
                    star = document.getElementsByClassName(class_name)[0]
                    if (i <= star_number) {
                        star.classList.add('checked');
                    }
                    else if (i > star_number) {
                        star.classList.remove('checked');
                    }
                }
            };
        </script>
        {% endif %}
    </div>
{% endblock %}

{% block script %}
{% endblock %}

webstore/templates/webstore/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <head>
        <title>{% block title %}GamerAsia{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'webstore/styles.css' %}" rel="stylesheet">
        <!-- Font Awesome Icon Library, star for rating -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">   
        {% block script %}
            <script src="{% static 'webstore/functions.js' %}"></script>
        {% endblock %}
    </head>
    <body style="max-width: 4096px;">
        <nav class="navbar navbar-expand-lg navbar-light" style="position: -webkit-sticky; position: sticky; top: 0; z-index: 1; background-color: rgba(255, 251, 247, 0.5); box-shadow: 0px 10px 15px 5px rgba(255, 234, 218, 0.5) inset;">
            <div class="row">
                <div>
                    <a class="navbar-brand" href="{% url 'webstore:index' page_number=1 %}">GamerAsia</a>
                </div>
            
                <div style="">
                    <ul class="navbar-nav mr-auto">
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'webstore:profile' %}">Welcome: {{ user.username }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'webstore:logout' %}">Logout</a>
                            </li>
                            {% if user.is_admin %}
                                <li class="nav-link" style="display: inline-block;">
                                    <form action="{% url 'webstore:new_item' %}">
                                        <button class="btn cart_and_item" style="height: 30px;font-size: 14px; padding: 1px;" type="submit"> +New item</button>
                                    </form>
                                </li>
                            {% endif %}
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'webstore:login' %}">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'webstore:register' %}">Register</a>
                            </li>
                        {% endif %}
                            <li class="nav-item" style="float: right;">
                                <a class="nav-link cart_icon"><img onclick="cart_popup()" src="https://image.flaticon.com/icons/svg/262/262611.svg" width="25" height="25" alt="Shopping cart" title="Shopping cart"> {{ num_in_cart }}</a>
                                <div id="cart_table" class="" style="position: absolute; height: 250px; width: 150px; border-radius: 20px; border: 1px solid #F9CBB3; padding: 5px; background-color: rgba(255, 254, 250, 0.9); text-align: center; visibility: hidden; -webkit-backface-visibility: hidden; -moz-backface-visibility: hidden;">
                                    <form action="{% url 'webstore:cart_detail' 1 %}">
                                        <button class="btn cart_and_item" style="height: 30px;font-size: 14px; padding: 1px;" type="submit"> Check Out</button>
                                    </form>
                                    <br>
                                    <form action="{% url 'webstore:cart_clear' %}">
                                        <button class="btn cart_and_item" style="height: 30px;font-size: 14px; padding: 1px;" type="submit"> Clear cart</button>
                                    </form>
                                </div>
                                <div hidden>
                                    Icons made by <a href="https://www.flaticon.com/authors/freepik" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a>
                                </div>
                            </li>
                    </ul>
                </div>
            </div>
          </nav>
        
        <div class="body">
            {% block body %}
            {% endblock %}
        </div>
        <script>
            // When the user clicks on div, open the popup
            function cart_popup() {
              var popup = document.getElementById("cart_table");
              if (popup.style.visibility != "hidden") {
                popup.style.visibility = "hidden";
                popup.style.visibility.backfaceVisibility = "hidden";
                popup.style.visibility.WebkitBackfaceVisibility = "hidden"; 
                popup.style.visibility.MozBackfaceVisibility = "hidden";

                popup.classList.remove('fade_in');
              }
              else {
                popup.style.visibility = "visible"
                popup.style.visibility.backfaceVisibility = "visible";
                popup.style.visibility.WebkitBackfaceVisibility = "visible"; 
                popup.style.visibility.MozBackfaceVisibility = "visible";

                popup.classList.add('fade_in');
              }
              
            }
            </script>
    </body>
</html>